import { Montserrat } from "next/font/google";
import { Vollkorn } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Navbar from "@/components/NavBar";
import { Toaster } from "react-hot-toast";

const montserrat = Montserrat({ subsets: ["latin"] });
// const vollkorn = Vollkorn({ subsets: ["latin"], variable: "--font-vollkorn" });

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${montserrat.className}`}
          style={{ backgroundColor: "#F8F7F4" }}
        >
          <div className="bg-white">
            <Navbar />
            <Toaster />

            {children}
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
